### ISSUE TITLE
Request to add 'linux-zen' and 'linux' packages

### ISSUE THREAD

**Issue by x0rzavi** [h0tc0d3/arch-packages#11]
Would it be possible for you to add these 2 packages?

**Comment by ptr1337** [comment]
Why ?

**Comment by h0tc0d3** [comment]
@x0rzavi I used only my own custom kernel. linux-zen unstable. I can't make  default kernel because i having 32gb memory, and build all packages in zram. I do not compile packages on nvme disk to extend their lifespan. Building an optimized full kernel takes about 100 GB of disk space. In zram it will be 50gb.

**Comment by x0rzavi** [comment]
@h0tc0d3 okay np. Anyways thanks for maintaining this repo.
